services:
  forum-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-web
    platform: linux/arm64/v8
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - forum-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:stable-alpine
    container_name: forum-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - forum-web
    networks:
      - forum-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  forum-network:
    driver: bridge